# Generated by Django 3.0.3 on 2020-02-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=63)),
                ('lastname', models.CharField(max_length=63)),
                ('job', models.CharField(blank=True, max_length=63, null=True)),
                ('pseudo', models.CharField(blank=True, max_length=63, null=True)),
                ('phone', models.CharField(blank=True, max_length=63, null=True)),
                ('insta', models.CharField(blank=True, max_length=63, null=True)),
                ('facebook', models.CharField(blank=True, max_length=63, null=True)),
                ('soundcloud', models.CharField(blank=True, max_length=63, null=True)),
                ('youtube', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('code', models.CharField(max_length=63, unique=True)),
                ('casting', models.ManyToManyField(to='vitrine.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('code', models.CharField(max_length=63, unique=True)),
                ('casting', models.ManyToManyField(to='vitrine.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtCompositing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('code', models.CharField(max_length=63, unique=True)),
                ('casting', models.ManyToManyField(to='vitrine.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
