# Generated by Django 3.0.3 on 2020-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcompositing',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
        migrations.AddField(
            model_name='artmapping',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='artcompositing',
            name='casting',
            field=models.ManyToManyField(blank=True, null=True, to='vitrine.Person'),
        ),
        migrations.AlterField(
            model_name='artmapping',
            name='casting',
            field=models.ManyToManyField(blank=True, null=True, to='vitrine.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(blank=True, null=True, to='vitrine.Person'),
        ),
    ]
