# Generated by Django 3.0.3 on 2020-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_auto_20200224_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcompositing',
            name='poster',
            field=models.ImageField(null=True, upload_to='poster/compositing/'),
        ),
        migrations.AddField(
            model_name='artmapping',
            name='poster',
            field=models.ImageField(null=True, upload_to='poster/mapping/'),
        ),
        migrations.AlterField(
            model_name='artcompositing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='artmapping',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
