# Generated by Django 3.0.3 on 2020-02-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_auto_20200224_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcompositing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_compositings', related_query_name='owned_compositings', to='vitrine.Person'),
        ),
        migrations.AddField(
            model_name='artmapping',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_mappings', related_query_name='owned_mappings', to='vitrine.Person'),
        ),
    ]
