# Generated by Django 3.0.3 on 2020-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_auto_20200224_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='team_contact',
            field=models.BooleanField(default=False),
        ),
    ]
