# Generated by Django 3.0.3 on 2020-02-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_person_team_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='camera_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_operators', related_query_name='camera_operators', to='vitrine.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composers', related_query_name='composers', to='vitrine.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', related_query_name='directors', to='vitrine.Person'),
        ),
    ]
