# Generated by Django 3.0.3 on 2020-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_auto_20200224_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artcompositing',
            name='video',
        ),
        migrations.RemoveField(
            model_name='artmapping',
            name='video',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='artcompositing',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artmapping',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
