# Generated by Django 3.0.3 on 2020-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0010_auto_20200828_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcompositing',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video/posters/'),
        ),
        migrations.AlterField(
            model_name='artmapping',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video/posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video/posters/'),
        ),
    ]
