# Generated by Django 3.1 on 2021-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0012_auto_20200830_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcompositing',
            name='youtube_api',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='artmapping',
            name='youtube_api',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_api',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
